"""links

Revision ID: 6943e7e43847
Revises: 3cdf5c81e4b4
Create Date: 2017-08-04 14:56:59.222105

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6943e7e43847'
down_revision = '3cdf5c81e4b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('link',
    sa.Column('from_location', sa.Integer(), nullable=True),
    sa.Column('to_location', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['from_location'], ['location.id'], ),
    sa.ForeignKeyConstraint(['to_location'], ['location.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('link')
    # ### end Alembic commands ###
